/*
 * @lc app=leetcode id=389 lang=java
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (52.72%)
 * Likes:    514
 * Dislikes: 230
 * Total Accepted:    147.9K
 * Total Submissions: 278K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */
class Solution {
  public char findTheDifference(String s, String t) {
    char c = t.charAt(t.length() - 1);
    for (int i = 0; i < s.length(); i++) {
      c ^= s.charAt(i);
      c ^= t.charAt(i);
    }
    return c;
  }
}

